### PR TITLE
Name Added

### PR DESCRIPTION
**Pull request by Srutip04**

### CODE REVIEW

**Comment by Ayan-thecodeking** [comment]
thnx @Srutip04  for contributing ..do share nd star this repo

**Review by Ayan-thecodeking — COMMENTED** [review]
there is a merge conflicts  in ur pr pls do solve that

**Comment by Srutip04** [comment]
The conflict is resolved

**Comment by Ayan-thecodeking** [comment]
> The conflict is resolved

Pls check it again ...you have removed Pranav name from contributing.md

**Pull request merged**
